version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
      time: "07:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
