apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: aktivitetsplan-fss
  namespace: {{namespace}}
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: aktivitetsplan/internal/isAlive
    initialDelay: 20
  readiness:
    path: aktivitetsplan/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: aktivitetsplan/internal/metrics
  ingresses:
    - https://aktivitetsplan-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/aktivitetsplan
  vault:
    enabled: true
  webproxy: true
  env:
    - name: DISABLE_PROXY
      value: 'true'
    - name: DISABLE_DECORATOR
      value: 'true'
    - name: CONFIGURATION_LOCATION
      value: '/decorator-fss.yaml'
  envFrom:
    - configmap: pto-config
