apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: aktivitetsplan
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: aktivitetsplan/internal/isAlive
    initialDelay: 60
  readiness:
    path: aktivitetsplan/internal/selftest
    initialDelay: 60
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: aktivitetsplan/internal/metrics
  ingresses:
    - https://aktivitetsplan.nav.no
    - https://tjenester.nav.no/aktivitetsplan
  vault:
    enabled: true
  webproxy: true
  env:
    - name: DITTNAV_LINK_URL
      value: 'https://tjenester.nav.no/dittnav/'
    - name: PUBLIC_STILLING_FRA_NAV_BASE_URL #hvis man endrer denne husk og endre deafult i js også
      value: 'https://www.nav.no/arbeid/stilling/'
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
