apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan
  namespace: pto
  labels:
    team: pto
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2025.11.04_13.31-0f88d7b95151
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      # Chrome does not send cookie with the site.webmanifest request, dont require login for that file
      autoLoginIgnorePaths:
        - /site.webmanifest
        - /assets/*
  tokenx:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  ingresses:
    - https://aktivitetsplan.ekstern.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
        - application: veilarblest
          namespace: dab
        - application: veilarbaktivitet
          namespace: dab
        - application: veilarbdialog
          namespace: dab
        - application: veilarboppfolging
          namespace: poao
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: navtestb2c.b2clogin.com
        - host: veilarbveileder.dev-fss-pub.nais.io
  gcp:
    buckets:
      - name: aktivitetsplan-dev
  envFrom:
    - configmap: pto-config
  env:
    - name: JSON_CONFIG
      # CSP for dekoratoren er hentet fra https://www.nav.no/dekoratoren/api/csp
      value: >
        {
          "gcs": {
            "bucketName": "nais-cdn-nav-dab-42cc",
            "bucketContextPath": "dab/aktivitetsplan-dev-ekstern/build/"
          },
          "dekorator": {
            "env": "dev",
            "simple": true,
            "chatbot": false
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "header": {
            "csp": {
              "defaultSrc":["'self'", "*.nav.no"],
              "scriptSrc":["*.nav.no","*.psplugin.com","*.hotjar.com","*.taskanalytics.com","'unsafe-inline'","'unsafe-eval'", "blob:", "*.boost.ai", "uxsignals-frontend.uxsignals.app.iterate.no"],
              "styleSrc":["*.nav.no","*.psplugin.com","'unsafe-inline'"],
              "fontSrc":["*.psplugin.com","*.hotjar.com","cdn.nav.no","data:"],
              "imgSrc":["*.nav.no","*.psplugin.com","*.vimeocdn.com","*.hotjar.com","www.vergic.com","data:","uxsignals-frontend.uxsignals.app.iterate.no"],
              "frameSrc":["*.hotjar.com","player.vimeo.com","video.qbrick.com"],
              "connectSrc":["*.nav.no","*.boost.ai","*.psplugin.com","*.hotjar.com","*.hotjar.io","*.taskanalytics.com","*.uxsignals.com"],
              "workerSrc": ["'self'", "*.nav.no", "blob:"]
            }
          },
          "cors": {
              "origin": ["https://oidc-ver2.difi.no"],
              "credentials": true,
              "maxAge": 7200,
              "allowedHeaders": ["Nav-Consumer-Id"]
            },
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "proxies": [
            { "fromPath": "/veilarbvedtakinfo", "toUrl": "https://veilarbvedtakinfo.dev-fss-pub.nais.io", "preserveFromPath": true, "toApp": {"name": "veilarbvedtakinfo", "namespace": "pto", "cluster": "dev-fss" } },
            {
                      "fromPath": "/veilarblest",
                      "toUrl": "http://veilarblest.dab.svc.cluster.local",
                      "preserveFromPath": true,
                      "toApp": {
                        "name": "veilarblest",
                        "namespace": "dab",
                        "cluster": "dev-gcp"
                      }
            },
            { "fromPath": "/veilarboppfolging", "toUrl": "http://veilarboppfolging.poao", "preserveFromPath": true, "toApp": {"name": "veilarboppfolging", "namespace": "poao", "cluster": "dev-gcp" } },
            { "fromPath": "/veilarbdialog", "toUrl": "http://veilarbdialog.dab", "preserveFromPath": true, "toApp": {"name": "veilarbdialog", "namespace": "dab", "cluster": "dev-gcp" } },
            { "fromPath": "/veilarbaktivitet", "toUrl": "http://veilarbaktivitet.dab", "preserveFromPath": true, "toApp": {"name": "veilarbaktivitet", "namespace": "dab", "cluster": "dev-gcp" } }
          ]
        }
