apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/aktivitetsplan/aktivitetsplan:{{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      # Chrome does not send cookie with the site.webmanifest request, dont require login for that file
      autoLoginIgnorePaths:
        - /site.webmanifest
  tokenx:
    enabled: true
  ingresses:
    - https://aktivitetsplan.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navtestb2c.b2clogin.com
  gcp:
    buckets:
      - name: aktivitetsplan-dev
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: JSON_CONFIG
      # CSP for dekoratoren er hentet fra https://www.nav.no/dekoratoren/api/csp
      value: >
        {
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "header": {
            "csp": {
              "defaultSrc":["'self'", "*.nav.no"],
              "scriptSrc":["*.nav.no","*.psplugin.com","*.hotjar.com","*.taskanalytics.com","'unsafe-inline'","'unsafe-eval'", "blob:", "*.boost.ai"],
              "styleSrc":["*.nav.no","*.psplugin.com","'unsafe-inline'"],
              "fontSrc":["*.psplugin.com","*.hotjar.com","cdn.nav.no","data:"],
              "imgSrc":["*.nav.no","*.psplugin.com","*.vimeocdn.com","*.hotjar.com","www.vergic.com"],
              "frameSrc":["*.hotjar.com","player.vimeo.com","video.qbrick.com"],
              "connectSrc":["*.nav.no","*.boost.ai","*.psplugin.com","*.hotjar.com","*.hotjar.io","*.taskanalytics.com"]
            }
          },
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "proxies": [
            { "fromPath": "/veilarbvedtakinfo", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarbvedtakinfo", "namespace": "pto", "cluster": "dev-fss" } },
            { "fromPath": "/veilarblest", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarblest", "namespace": "pto", "cluster": "dev-fss" } },
            { "fromPath": "/veilarboppfolging", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarboppfolging", "namespace": "pto", "cluster": "dev-fss" } },
            { "fromPath": "/veilarbdialog", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarbdialog", "namespace": "pto", "cluster": "dev-fss" } },
            { "fromPath": "/veilarbaktivitet", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarbaktivitet", "namespace": "pto", "cluster": "dev-fss" } }
          ],
          "redirects": [
              {
                "fromPath": "/api/auth",
                "toUrl": "/auth/info"
              },
              {
                "fromPath": "/aktivitetsplan",
                "toUrl": "{{AKTIVITETSPLAN_URL}}"
              },              {
                "fromPath": "/arbeidssokerregistrering",
                "toUrl": "{{ARBEIDSSOKERREGISTRERING_URL}}"
              },              {
                "fromPath": "/minside",
                "toUrl": "{{MINSIDE_URL}}"
              },              {
                "fromPath": "/veientilarbeid",
                "toUrl": "{{VEIENTILARBEID_URL}}"
              },              {
                "fromPath": "/arbeidsrettet-dialog",
                "toUrl": "{{ARBEIDSRETTET_DIALOG_URL}}",
                "preserveFromPath": "true"
              },
              {
                "fromPath": "/dialog",
                "toUrl": "{{ARBEIDSRETTET_DIALOG_URL}}",
                "preserveFromPath": "true"
              }
          ]
        }
