apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan-intern
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.04.14_11.14-66f2c0b9e68b
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingresses:
    - https://aktivitetsplan.intern.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navtestb2c.b2clogin.com
  gcp:
    buckets:
      - name: aktivitetsplan-dev-intern
  envFrom:
    - configmap: pto-config
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "aktivitetsplan-dev-intern"
          },
          "cors": {
             "origin": "https://veilarbpersonflate.intern.dev.nav.no"
           }
        }

