apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.04.14_11.14-66f2c0b9e68b
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      # Chrome does not send cookie with the site.webmanifest request, dont require login for that file
      autoLoginIgnorePaths:
        - /site.webmanifest
        - /assets/*
  tokenx:
    enabled: true
  ingresses:
    - https://aktivitetsplan.ekstern.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
        - application: poao-unleash
          namespace: poao
      external:
        - host: navtestb2c.b2clogin.com
        - host: veilarbdialog.dev-fss-pub.nais.io
        - host: veilarbaktivitet.dev-fss-pub.nais.io
        - host: veilarblest.dev-fss-pub.nais.io
        - host: veilarbmalverk.dev-fss-pub.nais.io
        - host: veilarbperson.dev-fss-pub.nais.io
        - host: veilarboppfolging.dev-fss-pub.nais.io
        - host: veilarbveileder.dev-fss-pub.nais.io
  gcp:
    buckets:
      - name: aktivitetsplan-dev
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: JSON_CONFIG
      # CSP for dekoratoren er hentet fra https://www.nav.no/dekoratoren/api/csp
      value: >
        {
          "gcs": {
            "bucketName": "aktivitetsplan-dev"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "header": {
            "csp": {
              "defaultSrc":["'self'", "*.nav.no"],
              "scriptSrc":["*.nav.no","*.psplugin.com","*.hotjar.com","*.taskanalytics.com","'unsafe-inline'","'unsafe-eval'", "blob:", "*.boost.ai", "uxsignals-frontend.uxsignals.app.iterate.no"],
              "styleSrc":["*.nav.no","*.psplugin.com","'unsafe-inline'"],
              "fontSrc":["*.psplugin.com","*.hotjar.com","cdn.nav.no","data:"],
              "imgSrc":["*.nav.no","*.psplugin.com","*.vimeocdn.com","*.hotjar.com","www.vergic.com","data:","uxsignals-frontend.uxsignals.app.iterate.no"],
              "frameSrc":["*.hotjar.com","player.vimeo.com","video.qbrick.com"],
              "connectSrc":["*.nav.no","*.boost.ai","*.psplugin.com","*.hotjar.com","*.hotjar.io","*.taskanalytics.com","*.uxsignals.com"]
            }
          },
          "cors": {
              "origin": ["https://oidc-ver2.difi.no"],
              "credentials": true,
              "maxAge": 7200,
              "allowedHeaders": ["Nav-Consumer-Id"]
            },
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "proxies": [
            { "fromPath": "/veilarbvedtakinfo", "toUrl": "https://veilarbvedtakinfo.dev-fss-pub.nais.io", "preserveFromPath": true, "toApp": {"name": "veilarbvedtakinfo", "namespace": "pto", "cluster": "dev-fss" } },
            { "fromPath": "/veilarblest", "toUrl": "https://veilarblest.dev-fss-pub.nais.io", "preserveFromPath": true, "toApp": {"name": "veilarblest", "namespace": "pto", "cluster": "dev-fss" } },
            { "fromPath": "/veilarboppfolging", "toUrl": "https://veilarboppfolging.dev-fss-pub.nais.io", "preserveFromPath": true, "toApp": {"name": "veilarboppfolging", "namespace": "pto", "cluster": "dev-fss" } },
            { "fromPath": "/veilarbdialog", "toUrl": "https://veilarbdialog.dev-fss-pub.nais.io", "preserveFromPath": true, "toApp": {"name": "veilarbdialog", "namespace": "pto", "cluster": "dev-fss" } },
            { "fromPath": "/veilarbaktivitet", "toUrl": "https://veilarbaktivitet.dev-fss-pub.nais.io", "preserveFromPath": true, "toApp": {"name": "veilarbaktivitet", "namespace": "pto", "cluster": "dev-fss" } }
          ]
        }
