apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan
  namespace: pto
  labels:
    team: pto
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.10.04_13.21-c31f6e652a0c
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      # Chrome does not send cookie with the site.webmanifest request, dont require login for that file
      autoLoginIgnorePaths:
        - /site.webmanifest
        - /assets/*
  tokenx:
    enabled:
      true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  ingresses:
    - https://aktivitetsplan.nav.no
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
        - application: veilarblest
          namespace: dab
        - application: veilarbaktivitet
          namespace: dab
        - application: veilarbdialog
          namespace: dab
        - application: veilarboppfolging
          namespace: poao
      external:
        - host: navnob2c.b2clogin.com
        - host: veilarbaktivitet.prod-fss-pub.nais.io
        - host: veilarbveileder.prod-fss-pub.nais.io
  gcp:
    buckets:
      - name: aktivitetsplan-prod
  envFrom:
    - configmap: pto-config
  env:
    - name: JSON_CONFIG
      # CSP for dekoratoren er hentet fra https://www.nav.no/dekoratoren/api/csp
      value: >
        {
          "gcs": {
            "bucketName": "nais-cdn-nav-dab-42cc",
            "bucketContextPath": "dab/aktivitetsplan-prod-ekstern/build/"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "header": {
            "csp": {
              "defaultSrc":["'self'", "*.nav.no"],
              "scriptSrc":["*.nav.no","*.psplugin.com","*.hotjar.com","*.taskanalytics.com","'unsafe-inline'","'unsafe-eval'", "blob:", "*.boost.ai", "uxsignals-frontend.uxsignals.app.iterate.no"],
              "styleSrc":["*.nav.no","*.psplugin.com","'unsafe-inline'"],
              "fontSrc":["*.psplugin.com","*.hotjar.com","cdn.nav.no","data:"],
              "imgSrc":["*.nav.no","*.psplugin.com","*.vimeocdn.com","*.hotjar.com","www.vergic.com","data:","uxsignals-frontend.uxsignals.app.iterate.no"],
              "frameSrc":["*.hotjar.com","player.vimeo.com","video.qbrick.com"],
              "connectSrc":["*.nav.no","*.boost.ai","*.psplugin.com","*.hotjar.com","*.hotjar.io","*.taskanalytics.com","*.uxsignals.com"]
            }
          },
          "cors": {
            "origin": ["https://oidc.difi.no"],
            "credentials": true,
            "maxAge": 7200,
            "allowedHeaders": ["Nav-Consumer-Id"]
          },
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "proxies": [
            { "fromPath": "/veilarbvedtakinfo", "toUrl": "https://veilarbvedtakinfo.prod-fss-pub.nais.io", "preserveFromPath": true, "toApp": {"name": "veilarbvedtakinfo", "namespace": "pto", "cluster": "prod-fss" } },
            {
              "fromPath": "/veilarblest",
              "toUrl": "http://veilarblest.dab.svc.cluster.local",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarblest",
                "namespace": "dab",
                "cluster": "prod-gcp"
              }
            },
            { "fromPath": "/veilarboppfolging", "toUrl": "http://veilarboppfolging.poao", "preserveFromPath": true, "toApp": {"name": "veilarboppfolging", "namespace": "poao", "cluster": "prod-gcp" } },
            { "fromPath": "/veilarbdialog", "toUrl": "http://veilarbdialog.dab", "preserveFromPath": true, "toApp": {"name": "veilarbdialog", "namespace": "dab", "cluster": "prod-gcp" } },
            { "fromPath": "/veilarbaktivitet", "toUrl": "http://veilarbaktivitet.dab", "preserveFromPath": true, "toApp": {"name": "veilarbaktivitet", "namespace": "dab", "cluster": "prod-gcp" } }
          ]
        }
