apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan-intern
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/aktivitetsplan/aktivitetsplan:{{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingresses:
    - https://aktivitetsplan.intern.nav.no
  gcp:
    buckets:
      - name: aktivitetsplan-prod-intern
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "aktivitetsplan-prod-intern"
          },
          "cors": {
             "origin": "https://veilarbpersonflate.intern.nav.no"
           }
        }
