
export const STATUS_BRUKER_ER_INTRESSERT = 'BRUKER_ER_INTERESSERT';
export const STATUS_PLANLAGT = 'PLANLAGT';
export const STATUS_GJENNOMFOERT = 'GJENNOMFOERT';
export const STATUS_FULLFOERT = 'FULLFOERT';
export const STATUS_AVBRUTT = 'AVBRUTT';

export const EGEN_AKTIVITET_TYPE = 'EGEN';
export const STILLING_AKTIVITET_TYPE = 'STILLING';
