export const STATUS_BRUKER_ER_INTRESSERT = 'BRUKER_ER_INTERESSERT';
export const STATUS_PLANLAGT = 'PLANLAGT';
export const STATUS_GJENNOMFOERT = 'GJENNOMFORES';
export const STATUS_FULLFOERT = 'FULLFORT';
export const STATUS_AVBRUTT = 'AVBRUTT';

export const EGEN_AKTIVITET_TYPE = 'EGEN';
export const STILLING_AKTIVITET_TYPE = 'STILLING';
export const TILTAK_AKTIVITET_TYPE = 'TILTAKSAKTIVITET';
export const GRUPPE_AKTIVITET_TYPE = 'GRUPPEAKTIVITET';
export const UTDANNING_AKTIVITET_TYPE = 'UTDANNINGSAKTIVITET';
export const SOKEAVTALE_AKTIVITET_TYPE = 'SOKEAVTALE';
export const IJOBB_AKTIVITET_TYPE = 'IJOBB';
export const BEHANDLING_AKTIVITET_TYPE = 'BEHANDLING';
export const MOTE_TYPE = 'MOTE';
export const SAMTALEREFERAT_TYPE = 'SAMTALEREFERAT';
export const STILLING_FRA_NAV_TYPE = 'STILLING_FRA_NAV';
export const EKSTERN_AKTIVITET_TYPE = 'EKSTERN_AKTIVITET';

export const INGEN_VALGT = 'INGEN_VALGT';
export const VENTER = 'VENTER';
export const SOKNAD_SENDT = 'SOKNAD_SENDT';
export const CV_DELT = 'CV_DELT';
export const INNKALT_TIL_INTERVJU = 'INNKALT_TIL_INTERVJU';
export const SKAL_PAA_INTERVJU = 'SKAL_PAA_INTERVJU';
export const AVSLAG = 'AVSLAG';
export const IKKE_FATT_JOBBEN = 'IKKE_FATT_JOBBEN';
export const JOBBTILBUD = 'JOBBTILBUD';

export const PROVER_VARSLING = 'PROVER_VARSLING';
export const HAR_VARSLET = 'HAR_VARSLET';
export const KAN_IKKE_VARSLE = 'KAN_IKKE_VARSLE';
export const HAR_SVART = 'HAR_SVART';
export const AVBRUTT_AV_SYSTEM = 'AVBRUTT_AV_SYSTEM';
export const AVBRUTT_AV_BRUKER = 'AVBRUTT_AV_BRUKER';

export const AVTALT_MED_NAV = 'AVTALT_MED_NAV';

export const JOBB_STATUS_HELTID = 'HELTID';
export const JOBB_STATUS_DELTID = 'DELTID';

export const TELEFON_KANAL = 'TELEFON';
export const OPPMOTE_KANAL = 'OPPMOTE';
export const INTERNET_KANAL = 'INTERNETT';

export enum TabId {
    AKTIVITETSPLAN = 'AKTIVITETSPLAN',
    DIALOG = 'DIALOG',
    VEDTAKSSTOTTE = 'VEDTAKSSTOTTE',
    DETALJER = 'DETALJER',
    ARBEIDSMARKEDSTILTAK = 'ARBEIDSMARKEDSTILTAK',
}
