/* eslint-disable */
export default { 'nb': { 
'advarsel.avbrutt.header': 'Avbrutt aktivitet',
'advarsel.fullfort.header': 'Flytt aktivitet til fullført',
'aktivitet-form.label.malverk': 'Ferdig utfylt aktivitet',
'aktivitet-form.lagre-og-publiser': 'Lagre og del',
'aktivitet-form.lagre': 'Lagre',
'aktivitet-form.pakrevd-felt-info': '* må fylles ut',
'aktivitet.avtaltmednav': 'Avtalt med NAV',
'aktivitet.etikett.aktuell': 'Søkt inn på tiltaket',
'aktivitet.etikett.avslag': 'Fått avslag',
'aktivitet.etikett.ikkaktuell': 'Ikke aktuell for tiltaket',
'aktivitet.etikett.ikkem': 'Ikke møtt på tiltaket',
'aktivitet.etikett.infomoete': 'Infomøte før tiltaket',
'aktivitet.etikett.ingen_valgt': 'Ingen',
'aktivitet.etikett.innkalt_til_intervju': 'Innkalt til intervju',
'aktivitet.etikett.jatakk': 'Takket ja til tilbud',
'aktivitet.etikett.jobbtilbud': 'Fått jobbtilbud',
'aktivitet.etikett.neitakk': 'Takket nei til tilbud',
'aktivitet.etikett.soknad_sendt': 'Søknaden er sendt',
'aktivitet.etikett.tilbud': 'Fått plass på tiltaket',
'aktivitet.etikett.venteliste': 'På venteliste',
'aktivitet.etikett': 'Etikett',
'aktivitet.form.ingen.utfylt.aktivitet.valgt': 'Ingen ferdig utfylt aktivitet valgt',
'aktivitet.ikkeavtaltmednav': 'Ikke avtalt med NAV',
'aktivitet.status.avbrutt': 'Avbrutt',
'aktivitet.status.bruker_er_interessert': 'Forslag',
'aktivitet.status.fullfort': 'Fullført',
'aktivitet.status.gjennomfores': 'Gjennomfører',
'aktivitet.status.planlagt': 'Planlegger',
'aktivitet.status': 'Status',
'aktivitet.type.arena_tiltak': 'Tiltak gjennom NAV',
'aktivitet.type.behandling': 'Medisinsk behandling',
'aktivitet.type.egen': 'Jobbrettet egenaktivitet',
'aktivitet.type.gruppeaktivitet': 'Gruppeaktivitet',
'aktivitet.type.ijobb': 'Jobb jeg har nå',
'aktivitet.type.midl_lonnstilskudd': 'Avtale midlertidig lønnstilskudd',
'aktivitet.type.mote': 'Møte med NAV',
'aktivitet.type.samtalereferat': 'Samtalereferat',
'aktivitet.type.sokeavtale': 'Avtale om å søke jobber',
'aktivitet.type.stilling_fra_nav': 'Stilling fra NAV',
'aktivitet.type.stilling': 'Stilling jeg skal søke',
'aktivitet.type.tiltaksaktivitet': 'Tiltak gjennom NAV',
'aktivitet.type.utdanningsaktivitet': 'Utdanning',
'aktivitetdetaljer.aarrangor-label': 'Arrangør',
'aktivitetdetaljer.adresse': 'Møtested eller annen praktisk informasjon',
'aktivitetdetaljer.ansettelsesforhold-label': 'Arbeidsgiver',
'aktivitetdetaljer.antall-dager-per-uke-label': 'Antall dager per uke',
'aktivitetdetaljer.antall-label': 'Antall søknader i perioden',
'aktivitetdetaljer.arbeidsgiver-label': 'Arbeidsgiver',
'aktivitetdetaljer.arbeidssted-label': 'Arbeidssted',
'aktivitetdetaljer.arbeidstid-label': 'Ansettelsesforhold',
'aktivitetdetaljer.avtale-oppfolging-label': 'Oppfølging fra NAV',
'aktivitetdetaljer.bakgrunn': 'Hensikt med møtet',
'aktivitetdetaljer.behandling-oppfolging-label': 'Oppfølging fra NAV',
'aktivitetdetaljer.behandling-sted-label': 'Behandlingssted',
'aktivitetdetaljer.behandling-type-label': 'Type behandling',
'aktivitetdetaljer.dato-tekst.gruppeaktivitet': 'Dato',
'aktivitetdetaljer.dato': 'Dato',
'aktivitetdetaljer.deltakelsesprosent-label': 'Deltakelse',
'aktivitetdetaljer.effekt-label': 'Mål for behandlingen',
'aktivitetdetaljer.forberedelser': 'Forberedelser til møtet',
'aktivitetdetaljer.fra-dato-tekst.default': 'Fra dato',
'aktivitetdetaljer.fra-dato-tekst.egen': 'Fra dato',
'aktivitetdetaljer.fra-dato-tekst.stilling': 'Fra dato',
'aktivitetdetaljer.hensikt-label': 'Mål med aktiviteten',
'aktivitetdetaljer.jobbStatus-DELTID': 'Deltid',
'aktivitetdetaljer.jobbStatus-HELTID': 'Heltid',
'aktivitetdetaljer.jobbStatus-label': 'Stillingsandel',
'aktivitetdetaljer.kanal': 'Møteform',
'aktivitetdetaljer.klokkeslett': 'klokkeslett',
'aktivitetdetaljer.kontaktperson-label': 'Kontaktperson',
'aktivitetdetaljer.lenke-label': 'Lenke',
'aktivitetdetaljer.moteplan-label': 'Tidspunkt og sted',
'aktivitetdetaljer.oppfolging-label': 'Min huskeliste',
'aktivitetdetaljer.status-label': 'Status',
'aktivitetdetaljer.sted-label': 'Sted',
'aktivitetdetaljer.til-dato-tekst.default': 'Til dato',
'aktivitetdetaljer.til-dato-tekst.egen': 'Til dato',
'aktivitetdetaljer.til-dato-tekst.stilling': 'Frist',
'aktivitetdetaljer.varighet': 'Varighet',
'aktivitetingress.behandling': 'Medisinsk behandling kan være behandling, oppfølging eller utredning hos fastlege, spesialist, fysioterapeut og lignende.',
'aktivitetingress.egen': '{underOppfolging, select,\ntrue { Her kan du eller veilederen din legge inn aktiviteter som hjelper deg når du skal komme i arbeid. Eksempler kan være å registrere deg hos bemannings- og rekrutteringsbyråer, jobbe godt med CV-en, eller lage oversikt over personer som kan være nyttig å kontakte når du er på jakt etter jobb. }\nfalse { Her kan du legge inn forskjellige egenaktiviteter du vil gjøre for å finne en ny jobb raskere. Eksempler kan være å ta en interessetest, registrere deg hos flere formidlingsbyråer eller lage en oversikt over nettverket ditt. }\n}',
'aktivitetingress.gruppeaktivitet': 'Her ser du informasjon om en gruppeaktivitet NAV har meldt deg på',
'aktivitetingress.ijobb': '{underOppfolging, select,\ntrue { Her kan du notere ned en deltidsjobb eller midlertidig stiling du har nå. Da kan vi følge deg opp bedre. Husk å føre opp de timene du har jobbet på meldekortet. }\nfalse { Her kan du notere ned en deltidsjobb eller midlertidig stiling du har nå, for å holde oversikten. }\n}',
'aktivitetingress.mote': 'NAV ønsker et møte med deg. Du må gi beskjed så raskt som mulig hvis tidspunktet ikke passer.',
'aktivitetingress.samtalereferat': 'Her finner du referat fra en samtale du har hatt med NAV.',
'aktivitetingress.sokeavtale': 'Her ser du hvor mange jobber NAV forventer at du søker. Legg inn hver stilling du søker i aktiviteten "En jobb jeg vil søke på".',
'aktivitetingress.stilling': 'Skriv inn informasjon om jobben du har lyst til å søke på her',
'aktivitetingress.tiltaksaktivitet': 'Her finner du informasjon om et tiltak NAV har søkt deg inn på.',
'aktivitetingress.utdanningsaktivitet': 'Her ser du informasjon om en utdanningsaktivitet eller et kurs NAV har registrert at du skal gjennomføre.',
'aktivitetkort.dato_label': '{ label, select,\nFRA {Fra:}\nTIL {Til:}\nother { {label}:}\n} {DATO}',
'aktivitetsdato.dato-etikett': 'dato',
'aktivitetsdato.vis-dato': '{fraDato} - {tilDato}',
'aktivitetsdato.vis-sett-dato': 'Legg inn til og fra dato',
'aktivitetskort.antall-label': 'Antall søknader i perioden:',
'aktivitetskort.type.behandling': 'Behandling',
'aktivitetskort.type.egen': 'Jobbrettet egenaktivitet',
'aktivitetskort.type.gruppeaktivitet': 'Gruppeaktivitet',
'aktivitetskort.type.ijobb': 'Jobb jeg har nå',
'aktivitetskort.type.mote': 'Møte med NAV',
'aktivitetskort.type.samtalereferat': 'Samtalereferat',
'aktivitetskort.type.sokeavtale': 'Jobbsøking',
'aktivitetskort.type.stilling': 'Stilling',
'aktivitetskort.type.tiltaksaktivitet': 'Tiltak gjennom NAV',
'aktivitetskort.type.utdanningsaktivitet': 'Utdanning',
'aktivitetsmal.avbryt': 'Avbryt',
'aktivitetsmal.lagre': 'Lagre',
'aktivitetsmal.mangler-historisk-mal': 'Mål er ikke lagt inn for denne perioden',
'aktivitetsmal.mitt-mal-deafult': 'Du har ikke skrevet hva målet ditt er. Beskriv målet ditt, gjerne både kortsiktige og langsiktige mål og hva slags arbeidsoppgaver du ønsker deg.',
'aktivitetsmal.mitt-mal-disabled': 'Trykk her for å se dine tidligere mål',
'aktivitetsmal.mitt-mal.header': 'Mitt mål',
'aktivitetsmal.mitt-mal': 'Mitt mål',
'aktivitetsmal.opprett-mal-tekst': 'Legg inn målet ditt for aktivitet og jobb. Beskriv gjerne både kortsiktige og langsiktige mål og hva slags arbeidsoppgaver du ønsker deg.',
'aktivitetsmal.opprett-mal': 'Opprett ditt mål',
'aktivitetsmal.opprett': 'Opprett',
'aktivitetsmal.rediger': 'Rediger',
'aktivitetsmal.skjul': 'Skjul tidligere lagrede mål',
'aktivitetsmal.skrevet-av': 'Skrevet av',
'aktivitetsmal.slettet-av': 'Mål slettet av',
'aktivitetsmal.tekst.label': '{underOppfolging, select,\ntrue { Når du og NAV er enige om målet ditt, kan vi samarbeide om aktuelle aktiviteter. }\nfalse { Legg inn hva slags arbeidsoppgaver og stillinger du ser etter. }\n}',
'aktivitetsmal.tekst.makslengde.feilmelding': 'Du må korte ned teksten til {antall_tegn} tegn',
'aktivitetsmal.vis': 'Vis tidligere lagrede mål',
'aktivitetsmodal.kan.ikke.redigeres': 'Denne aktiviteten kan ikke redigeres.',
'aktivitetstatus.bekreft-knapp': 'Bekreft',
'aktivitetstatus.form.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'aktivitetstatus.mangler-publisering-av-samtalereferat.MOTE': 'Du må dele referatet med brukeren før du kan sette aktiviteten til fullført',
'aktivitetstatus.mangler-publisering-av-samtalereferat.SAMTALEREFERAT': 'Du må dele referatet med brukeren før du kan sette aktiviteten til fullført eller avbrutt',
'aktivitetstatus.oppdater-status-advarsel': 'Hvis du endrer til "Fullført" eller "Avbrutt", blir aktiviteten låst og du kan ikke lenger endre innholdet.',
'aktivitetstatus.oppdater-status-begrunnelse': '{valgtAktivitetStatus, select,\nFULLFORT{Skriv en kort kommentar om hvordan det har gått med aktiviteten, eller noe NAV bør kjenne til.}\nAVBRUTT{Skriv en kort begrunnelse om hvorfor du avbrøt aktiviteten. Etter at du har trykket på "Bekreft", må du gi beskjed til veilederen din ved å starte en dialog her i aktivitetsplanen.}\nother {Skriv en kort begrunnelse om hvorfor aktiviteten ble satt til {valgtAktivitetStatus}.}\n }',
'aktivitetstavle.AVBRUTT': 'Avbrutt',
'aktivitetstavle.BRUKER_ER_INTERESSERT': 'Forslag',
'aktivitetstavle.FULLFORT': 'Fullført',
'aktivitetstavle.GJENNOMFORES': 'Gjennomfører',
'aktivitetstavle.PLANLAGT': 'Planlegger',
'aktivitetstavle.avbrutt.info': 'Informasjon om statusen Avbrutt',
'aktivitetstavle.brukerErInteressert.info': 'Informasjon om statusen Forslag',
'aktivitetstavle.fullfoert.info': 'Informasjon om statusen Fullført',
'aktivitetstavle.gjennomfoert.info': 'Informasjon om statusen Gjennomfører',
'aktivitetstavle.planlagt.info': 'Informasjon om statusen Planlegger',
'aktivitetstavle.print.avbrutt': 'Avbrutte aktiviteter',
'aktivitetstavle.print.bruker_er_interessert': 'Forslag til aktiviteter',
'aktivitetstavle.print.fullfort': 'Fullførte aktiviteter',
'aktivitetstavle.print.gjennomfores': 'Aktiviteter jeg gjennomfører nå',
'aktivitetstavle.print.planlagt': 'Planlagte aktiviteter',
'aktivitetstavle.scrollknapp.forrige.label': 'Flytt visning en kolonne til venstre',
'aktivitetstavle.scrollknapp.neste.label': 'Flytt visning en kolonne til høyre',
'aktivitetvisning.administreres-av-veileder': 'Ta kontakt med NAV hvis det er noe som er til hinder for at du kan begynne på eller fullføre denne aktiviteten. Du kan ikke oppdatere status for denne aktiviteten selv.',
'aktivitetvisning.beskrivelse-label': 'Beskrivelse',
'aktivitetvisning.dialog-knapp': 'Dialog',
'aktivitetvisning.endre-knapp': 'Endre',
'aktivitetvisning.header': '{ status, select,\nPLANLAGT { Planlegger }\nBRUKER_ER_INTERESSERT { Forslag }\nGJENNOMFORES { Gjennomfører }\nFULLFORT { Fullført }\nAVBRUTT { Avbrutt }\nother { {status} }\n} / { type, select,\nEGEN { Jobbrettet egenaktivitet }\nSTILLING { Stilling }\nTILTAKSAKTIVITET { Tiltak gjennom NAV}\nGRUPPEAKTIVITET { Gruppeaktivitet }\nUTDANNINGSAKTIVITET { Utdanning }\nSOKEAVTALE { Jobbsøking }\nIJOBB { Jobb jeg har nå }\nBEHANDLING { Behandling }\nMOTE { Møte med NAV }\nSAMTALEREFERAT { Samtalereferat }\nother { {type} }\n}',
'aktivitetvisning.historikk-knapp': 'Endringslogg',
'aktivitetvisning.lagre-knapp': 'Lagre',
'aktkivitet-skjema.lukk-advarsel': 'Alle endringer blir borte hvis du ikke lagrer. Er du sikker på at du vil lukke siden?',
'arbeidsavtale.form.frist': 'Frist',
'arbeidsliste-form.feilmelding.kommentar-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'arbeidsliste-form.feilmeleding.frist.etter': 'Fristen må være i dag eller senere',
'arbeidsliste.modal.personalia': '{navn}, {fnr}',
'arbeidsliste.modal.rediger.overskrift': 'Rediger',
'arbeidsliste.overskrift.feilmelding.for-kort': 'Du må fylle ut en tittel',
'arbeidsliste.overskrift': 'Tittel',
'begrunnelse-aktivitet.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'begrunnelse-aktivitet.modal.lagre': 'LAGRE',
'behandling-aktivitet-form.default-tittel': 'Medisinsk behandling',
'behandling-aktivitet-form.feilmelding.behandling-sted-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'behandling-aktivitet-form.feilmelding.behandling-type-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'behandling-aktivitet-form.feilmelding.beskrivelse-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'behandling-aktivitet-form.feilmelding.effekt-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'behandling-aktivitet-form.feilmelding.oppfolging-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'behandling-aktivitet-form.feilmelding.paakrevd-behandling-sted': 'Du må fylle ut behandlingssted',
'behandling-aktivitet-form.feilmelding.paakrevd-behandling-type': 'Du må fylle ut type behandling',
'behandling-aktivitet-form.feilmelding.paakrevd-fradato': 'Du må fylle ut fra dato',
'behandling-aktivitet-form.feilmelding.paakrevd-tildato': 'Du må fylle ut til dato. Hvis du ikke vet når behandlingen avsluttes, kan du legge inn en foreløpig til dato.',
'behandling-aktivitet-form.header': 'Medisinsk behandling',
'behandling-aktivitet-form.label.avtale-oppfolging': 'Oppfølging fra NAV',
'behandling-aktivitet-form.label.behandling-sted': 'Behandlingssted *',
'behandling-aktivitet-form.label.behandling-type': 'Type behandling *',
'behandling-aktivitet-form.label.beskrivelse': 'Kort beskrivelse av behandlingen',
'behandling-aktivitet-form.label.effekt': 'Mål for behandlingen',
'behandling-aktivitet-form.label.fra-dato': 'Fra dato *',
'behandling-aktivitet-form.label.til-dato': 'Til dato *',
'components.filterform.button.lukk': 'Lukk',
'components.filterform.button.nullstill': 'Nullstill',
'components.filterform.button.velg': 'Velg',
'datepicker.feilmelding.egen.fradato-etter-frist': 'Fra dato kan ikke være etter til dato',
'datepicker.feilmelding.gammel-fra-dato': 'Datoen er for langt tilbake i tid',
'datepicker.feilmelding.ijobb.fradato-etter-frist': 'Fra dato kan ikke være etter til dato',
'datepicker.feilmelding.innenfor-periode': 'Datoen må være innenfor perioden {fradato}-{tildato}',
'datepicker.feilmelding.stilling.fradato-etter-frist': 'Fra dato kan ikke være etter søknadsfrist',
'datepicker.feilmelding.ugyldig-dato': 'Datoen du har oppgitt er ikke en gyldig dato',
'datepicker.forrige-maaned': 'Forrige måned',
'datepicker.neste-maaned': 'Neste måned',
'dialog.deg-og-nav.tittel': 'Dialog med NAV',
'dialog.eskalering.overskrift': 'Du har fått et varsel fra NAV',
'dialog.eskalerings-filter': 'Viktige meldinger',
'dialog.eskalert-melding': 'Viktig melding',
'dialog.ferdigbehandlet': 'Ferdigbehandlet',
'dialog.henvendelse.topp': '{ visveileder, select,\n  true { {dato} - Skrevet av {veileder} }\n  other { {dato} }\n}',
'dialog.ikke-ferdigbehandlet': 'Venter på svar fra NAV',
'dialog.info-til-bruker': 'Henvendelsen er sendt. Du kan forvente svar i løpet av noen dager.',
'dialog.ingress': 'Ingress som ska visas før bruker',
'dialog.lag-ny-dialog': 'Send',
'dialog.lest-av-bruker': 'Lest av bruker',
'dialog.modal.lukk-dialog': 'Lukk dialog',
'dialog.modal.lukk-ny-dialog': 'Lukk ny dialog',
'dialog.modal.ny-dialog': 'Ny dialog',
'dialog.modal.til-aktiviteten': 'Aktivitet: {tittel}',
'dialog.modal.tilbake': 'Tilbake til dialoglisten',
'dialog.ny-dialog': 'Ny dialog',
'dialog.ny-henvendelse.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'dialog.ny-henvendelse.overskrift.for-lang.feilmelding': 'Du må korte ned teksten til {antall_tegn} tegn',
'dialog.ny-henvendelse.overskrift.mangler.feilmelding': 'Du må fylle ut tema',
'dialog.ny-henvendelse.tekst.for-lang.feilmelding': 'Du må korte ned teksten til {antall_tegn} tegn',
'dialog.ny-henvendelse.tekst.mangler.feilmelding': 'Du må fylle ut en melding',
'dialog.overskrift-label': 'Tema',
'dialog.tekst-label-aktivitet': '{erVeileder, select,\ntrue {Skriv en melding til brukeren}\nfalse {Skriv en melding til NAV-kontoret ditt om denne aktiviteten}\n}',
'dialog.tekst-label-generell': '{erVeileder, select,\ntrue {Skriv en melding til brukeren}\nfalse {Skriv en melding til NAV-kontoret ditt om arbeid og oppfølging}\n}',
'dialog.tekst-label': 'Skriv en melding som gjelder arbeid og oppfølging fra NAV-kontoret',
'dialog.tittel': '{ motpart, select,\nNAV { Dialog mellom deg og NAV }\nother { Dialog med {motpart} }\n}',
'dialog.venter-pa-svar-etikett': '{erVeileder, select,\ntrue {Venter på svar fra bruker}\nfalse {NAV venter på svar fra deg}\n}',
'dialog.venter-pa-svar': 'Venter på svar fra bruker',
'dialoggruppe.leste-meldinger': 'Leste meldinger',
'dialoggruppe.nye-meldinger': 'Nye meldinger',
'egen-aktivitet-form.feilmelding.beskrivelse-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'egen-aktivitet-form.feilmelding.hensikt-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'egen-aktivitet-form.feilmelding.lenke-lengde': 'Lenken kan ikke være lenger enn {MAKS_LENGDE} tegn',
'egen-aktivitet-form.feilmelding.oppfolging-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'egen-aktivitet-form.feilmelding.paakrevd-fradato': 'Du må fylle ut fra dato',
'egen-aktivitet-form.feilmelding.paakrevd-tildato': 'Du må fylle ut til dato',
'egen-aktivitet-form.feilmelding.paakrevd-tittel': 'Du må fylle ut navn på aktiviteten',
'egen-aktivitet-form.feilmelding.tittel-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'egen-aktivitet-form.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'egen-aktivitet-form.header': 'Jobbrettet egenaktivitet',
'egen-aktivitet-form.label.beskrivelse': 'Kort beskrivelse av aktiviteten',
'egen-aktivitet-form.label.fra-dato': 'Fra dato *',
'egen-aktivitet-form.label.hensikt': 'Mål med aktiviteten',
'egen-aktivitet-form.label.lenke': 'Lenke til en aktuell nettside',
'egen-aktivitet-form.label.oppfolging': 'Min huskeliste for denne aktiviteten',
'egen-aktivitet-form.label.overskrift': 'Navn på aktiviteten *',
'egen-aktivitet-form.label.til-dato': 'Til dato *',
'endre-aktivitet.overskrift': 'Endre aktivitet',
'endre-aktivitet.tilbake': 'Tilbake',
'endringer.skjul': 'Vis mindre',
'endringer.vis-mer': 'Vis mer',
'endringstype.AVTALT_DATO_ENDRET': 'endret til dato på aktiviteten fra { fra } til { til }',
'endringstype.AVTALT': 'merket aktiviteten som "Avtalt med NAV"',
'endringstype.BLE_HISTORISK': 'arkiverte aktiviteten',
'endringstype.DETALJER_ENDRET': 'endret detaljer på aktiviteten',
'endringstype.ETIKETT_ENDRET': 'endret tilstand til { til, select,\nINGEN_VALGT { Ingen }\nSOKNAD_SENDT { Søknaden er sendt }\nINNKALT_TIL_INTERVJU { Skal på intervju }\nAVSLAG { Fått avslag }\nJOBBTILBUD { Fått jobbtilbud }\nother { {til} }\n}',
'endringstype.MOTE_TID_OG_STED_ENDRET': 'endret tid eller sted for møtet',
'endringstype.OPPRETTET': 'opprettet aktiviteten',
'endringstype.REFERAT_ENDRET': 'endret referatet',
'endringstype.REFERAT_OPPRETTET': 'opprettet referat',
'endringstype.REFERAT_PUBLISERT': 'delte referatet',
'endringstype.STATUS_ENDRET': 'flyttet aktiviteten fra { fra, select,\n    BRUKER_ER_INTERESSERT { forslag }\n    PLANLAGT { planlegger }\n    GJENNOMFORES { gjennomfører }\n    FULLFORT { fullført }\n    AVBRUTT { avbrutt }\n    other { {fra} }\n} til { til, select,\n    BRUKER_ER_INTERESSERT { forslag }\n    PLANLAGT { planlegger }\n    GJENNOMFORES { gjennomfører }\n    FULLFORT { fullført }\n    AVBRUTT { avbrutt }\n    other { {til}}\n}',
'etikett.AKTUELL': 'Søkt inn på tiltaket',
'etikett.AVSLAG': 'Fått avslag',
'etikett.IKKAKTUELL': 'Ikke aktuell for tiltaket',
'etikett.IKKEM': 'Ikke møtt på tiltaket',
'etikett.INFOMOETE': 'Infomøte før tiltaket',
'etikett.INGEN_VALGT': 'Ingen',
'etikett.INNKALT_TIL_INTERVJU': 'Innkalt til intervju',
'etikett.JATAKK': 'Takket ja til tilbud',
'etikett.JOBBTILBUD': 'Fått jobbtilbud',
'etikett.NEITAKK': 'Takket nei til tilbud',
'etikett.SOKNAD_SENDT': 'Søknaden er sendt',
'etikett.TILBUD': 'Fått plass på tiltaket',
'etikett.VENTELISTE': 'På venteliste',
'etikettstatus.bekreft-knapp': 'Bekreft',
'feilmelding.opprett-oppgave.beskrivelse.for.lang': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'feilmelding.opprett-oppgave.beskrivelse.pakrevd': 'Du må fylle ut en beskrivelse',
'ferdigstilt.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'ferdigstilt.modal.lagre': 'Lagre',
'ferdigstilt.modal.message': 'Når du lagrer, blir aktiviteten låst og du kan ikke lenger endre innholdet.',
'filter.aktivitet.avtalt.tittel': 'Avtalt aktivitet',
'filter.aktivitet.etikett.tittel': 'Tilstand',
'filter.aktivitet.type.tittel': 'Aktivitetstype',
'filter.periode.inneverende': 'Nåværende periode',
'filter.periode.tittel': 'Velg periode',
'filter.tittel': 'Filtrer',
'forhandsorienterin.arenaaktivitet.er-sendt': 'Forhåndsorientering for $11-9 (AAP) er sendt.',
'forhandsorientering.arenaaktivitet.bekreft-og-send': 'Bekreft og send',
'forhandsorientering.arenaaktivitet.checkbox': 'Send forhåndsorientering for §11-9 (AAP)',
'forhandsorientering.arenaaktivitet.mindre-enn-syv-dager': 'Du kan ikke sende forhåndsorientering fordi sluttdatoen er satt til mindre enn 7 dager fram i tid. Hvis du skal sende forhåndsorientering etter §11-9 må det dokumenteres i samtalereferat eller dialog i aktivitetsplan.',
'forhandsorientering.arenaaktivitet.tittel': 'Tiltaket er automatisk merket "Avtalt med NAV"',
'har.ikke.aktivitetsplan.advarsel.bruker': 'Du må være registrert hos NAV for å bruke aktivitetsplanen.',
'har.ikke.aktivitetsplan.advarsel.veileder': 'Denne brukeren er ikke registrert.',
'hjelpetekst.aktivitet.avbrutt': 'Dra aktiviteter hit som du avbryter eller ikke begynner på. Flytter du en aktivitet til Avbrutt, blir den låst og kan ikke redigeres. Hvis du angrer, kan du opprette en tilsvarende ny aktivitet.',
'hjelpetekst.aktivitet.er.interessert': 'Legg til en aktivitet du tror du kommer til å gjøre her. Dra aktiviteten til Planlegger når du har bestemt deg for å gjøre aktiviteten.',
'hjelpetekst.aktivitet.fullfoert': 'Dra aktiviteter som du er ferdig med hit. Flytter du en aktivitet til Fullført, blir den låst og kan ikke redigeres. Hvis du angrer, kan du opprette en ny tilsvarende aktivitet.',
'hjelpetekst.aktivitet.gjennomfoert': 'Dra aktiviteter hit som du gjennomfører nå. Har du søkt på en stilling og venter på et svar, kan du vente med å dra aktiviteten til Fullført til du har fått svaret.',
'hjelpetekst.aktivitet.planlagt': 'Legg til en aktivitet som du faktisk planlegger å gjøre her. Når du starter aktiviteten, drar du den til Gjennomfører.',
'hjelpetekst.tittel.aktivitet.apen': 'Aktiviteten er ikke låst og kan flyttes.',
'hjelpetekst.tittel.aktivitet.last': 'Aktiviteten er låst og kan ikke flyttes.',
'hovedside.tittel': 'Aktivitetsplan',
'identitet.deg': 'deg',
'ijobb-aktivitet-form.feilmelding.ansettelsesforhold-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'ijobb-aktivitet-form.feilmelding.arbeidstid-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'ijobb-aktivitet-form.feilmelding.beskrivelse-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'ijobb-aktivitet-form.feilmelding.paakrevd-fradato': 'Du må fylle ut fra dato',
'ijobb-aktivitet-form.feilmelding.paakrevd-jobbStatus': 'Du må velge heltid eller deltid',
'ijobb-aktivitet-form.feilmelding.paakrevd-tildato': 'Du må fylle ut til dato. Hvis du har en fast stilling, kan du for eksempel legge inn til dato ett år frem i tid.',
'ijobb-aktivitet-form.feilmelding.paakrevd-tittel': 'Du må fylle ut stillingstittel',
'ijobb-aktivitet-form.feilmelding.typeStilling-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'ijobb-aktivitet-form.header': 'Jobb jeg har nå',
'ijobb-aktivitet-form.label.ansettelsesforhold': 'Arbeidsgiver',
'ijobb-aktivitet-form.label.arbeidstid': 'Ansettelsesforhold (fast, midlertidig, vikariat)',
'ijobb-aktivitet-form.label.beskrivelse': 'Kort beskrivelse av arbeidstid (dag, kveld, helg, stillingsprosent) og arbeidsoppgaver',
'ijobb-aktivitet-form.label.fra-dato': 'Fra dato *',
'ijobb-aktivitet-form.label.jobbStatus': 'Stillingsandel *',
'ijobb-aktivitet-form.label.overskrift': 'Stillingstittel *',
'ijobb-aktivitet-form.label.til-dato': 'Til dato',
'ikke.under.oppfolging.reaktivering.lenke': 'Register deg hos NAV',
'ikke.under.oppfolging.reaktivering': 'Du er ikke lenger registrert hos NAV og din tidligere aktivitetsplan er lagt under "Tidligere planer". Hvis du fortsatt skal motta ytelser, få oppfølging fra NAV og bruke aktivitetsplanen må du være registrert.',
'informasjon-mer-lenke': 'aktivitetsplanen',
'informasjon-mer': 'Se video om',
'informasjon.hjelpetekst': 'I aktivitetsplanen kan du holde orden på jobbsøkeraktiviteter og andre aktiviteter du gjør i samarbeid med NAV. Se video eller les teksten under om aktivitetsplanen.',
'informasjon.informasjonstekst.seksjon.bruk': '<p>Det første du bør gjøre er å bestemme deg for hva som er målet ditt. Tenk over hvilke jobber du kan trives i og som du tror passer for deg. Når du har definert et mål, kan du vurdere hvilke aktiviteter som må til for at du skal nå dette målet. Eksempler på aktiviteter kan være å søke jobber, kortere kurs og arbeidstrening. Aktivitetsplanen skal hjelpe deg med å strukturere og holde oversikt over aktivitetene dine.</p>\n\n<p>Aktivitetsplanen er delt inn i fem kolonner med statusene forslag, planlegger, gjennomfører, fullført og avbrutt. Du flytter en aktivitet fra en kolonne til en annen ved å dra og slippe aktiviteten, eller ved å velge status inne i aktiviteten. På denne måten viser du fremdriften i aktivitetene du skal gjennomføre.</p>\n\n<p>Du kan selv legge inn aktiviteter i planen. NAV kan også foreslå aktiviteter for deg som du selv velger om du vil gjennomføre. I tillegg kan veilederen din legge til aktiviteter som du er forpliktet til å gjennomføre. Disse aktivitetene vil ha en blå etikett som heter «Avtalt med NAV». Du kan ikke gjøre endringer i slike aktiviteter. Hvis du er uenig i at en aktivitet er merket som avtalt, kan du skrive i dialogen og forklare hvorfor du er uenig.</p>\n\n<p>Noen ganger vil aktivitetene være merket med en blå prikk. Det betyr at veilederen din har gjort en endring.</p>',
'informasjon.informasjonstekst.seksjon.meldekort': '<p>Hvis du får dagpenger, tiltakspenger eller er arbeidssøker, skal du oppgi tiltak, kurs eller utdanning på meldekortet. Aktivitetsplanen din kan inneholde flere avtalte aktiviteter enn det meldekortet spør deg om. Det kan for eksempel gjelde jobber du skal søke på eller oppdatering av CV-en din.</p>\n\n<p>Hvis du får arbeidsavklaringspenger, skal du føre opp alle aktiviteter du har gjort på meldekortet.</p>\n\n<p>Her kan du lese <a href="https://www.nav.no/no/Person/Arbeid/Dagpenger+ved+arbeidsloshet+og+permittering/Meldekort+hvordan+gjor+du+det">mer informasjon om meldekort</a>.</p>',
'informasjon.informasjonstekst.seksjon.personvern': '<p>Når du henvender deg til NAV fordi du trenger hjelp til å komme i jobb, skal NAV vurdere behovet ditt for hjelp.</p>\n\n<p>Du har rett til å få en aktivitetsplan. Alle som ikke har reservert seg fra digital kommunikasjon med det offentlige, skal bruke aktivitetsplanen og kommunisere med NAV gjennom den. Du kan få manuell oppfølging hvis det er gode grunner til det. Manuell oppfølging betyr at en veileder følger deg opp uten at du har en digital aktivitetsplan. Veilederen vil legge inn aktiviteter, møtereferat og fylle inn målet ditt i aktivitetsplanen for deg. Du får da aktivitetsplanen i papirform.</p>\n\n<p>Opplysningene i aktivitetsplanen, slik som aktiviteter, målet ditt og dialogen mellom deg og veilederen din, er det du og NAV som legger inn. Formålet med disse opplysningene er å hjelpe deg å komme raskt i jobb. Opplysningene dine blir ikke delt med andre instanser eller etater, med mindre de har lovlig grunnlag til å samle inn slike opplysninger.</p>\n\n<p>NAV henter også informasjon fra Folkeregisteret for å gjøre en sjekk mot Kontakt- og reservasjonsregisteret. Dette gjør vi for å se om du har reservert deg mot digital kommunikasjon med det offentlige. </p>\n\n<p>Opplysningene i aktivitetsplanen din blir lagret og oppbevart etter arkivloven. Aktiviteter og meldinger i dialogen kan ikke slettes når de først er opprettet.</p>\n\n<p>Les mer om <a href="https://www.nav.no/no/NAV+og+samfunn/Om+NAV/personvern-i-arbeids-og-velferdsetaten">hvordan NAV behandler personopplysninger</a>.</p>',
'informasjon.informasjonstekst.seksjon.ytelser': '<p>Aktivitetsplanen og dialogen skal kun handle om jobbrettede aktiviteter. Du skal derfor ikke skrive om økonomisk støtte, økonomisk sosialhjelp, boligsituasjon eller andre ting som ikke handler om jobb.</p>\n\n<p>\n <ul>\n    <li>Bruk nav.no til å finne svar på disse spørsmålene. Hvis du ikke finner svaret der, kan du ringe oss på 55 55 33 33.</li>\n    <li>Hvis du ikke følger opp avtalte aktiviteter, kan det få konsekvenser for oppfølgingen du får fra NAV og eventuell økonomisk støtte.</li>\n </ul>\n</p>',
'informasjon.informasjonstekst.tittel': 'Personvernerklæring for Arbeids- og velferdsetaten',
'informasjon.ny_hjelpetekst': '<p>Aktivitetsplanen din er verktøyet du skal bruke for å komme i aktivitet og jobb. Denne blir delt med veilederen din. For at vi skal kunne følge deg opp best mulig, er det viktig at du bruker aktivitetsplanen aktivt. Du må gjennomføre de aktivitetene du avtaler med NAV i planen.</p>\n\n<p>Du kan selv legge inn og redigere målet ditt, aktiviteter du skal gjøre og stillinger du vil søke på. Du får også tilgang til en dialog der du kan kommunisere med veilederen din og diskutere aktiviteter du skal gjennomføre.</p>',
'informasjon.ny_tittel': 'Hva er aktivitetsplanen?',
'informasjon.tittel.seksjon.bruk': 'Slik bruker du planen',
'informasjon.tittel.seksjon.meldekort': 'Meldekort',
'informasjon.tittel.seksjon.personvern': 'Rettigheter og personvern',
'informasjon.tittel.seksjon.ytelser': 'Aktivitetsplanen og økonomisk støtte',
'informasjon.tittel': 'Informasjon',
'informasjon.videokontent.skjul.tekst': 'Skjul teksten for videoen',
'informasjon.videokontent.text': '<ul>\n    <li>For at du skal holde oversikt og vite hva som forventes av deg, og kunne samarbeide med veilederen din, har vi laget en aktivitetsplan på nav.no</li>\n    <li>Aktivitetsplan er et verktøy du kan bruke for å komme deg ut i jobb, enten det er fort gjort eller om det kreves litt mer langsiktig planlegging.</li>\n    <li>Du setter deg mål, lager planer og legger inn oppgaver du skal gjennomføre.</li>\n    <li>Dette gjør du enkelt på små kort som du kan dra og slippe, avhengig av hva du har gjort så langt.</li>\n    <li>Og det fine er, at du kan dele alt med veilederen din så dere sammen kan diskutere det neste steget ditt.</li>\n    <li>Du og veilederen din samarbeider om aktivitetsplanen når dere møtes, og hver for dere.</li>\n    <li>Dere kan diskutere kortene og du får varsling når du har fått svar.</li>\n    <li>Målet er at du skal få en jobb på den måten som passer best for deg og din situasjon.</li>\n    <li>Lykke til!</li>\n</ul>',
'informasjon.videokontent.tittel': 'Les teksten i videoen',
'informasjon.videokontent.vis.tekst': 'Vis tekst for video',
'kanal.internett': 'Videomøte',
'kanal.oppmote': 'Oppmøte',
'kanal.telefon': 'Telefonmøte',
'lagtInnAv.BRUKER.bruker': 'Du',
'lagtInnAv.BRUKER.veileder': 'Bruker',
'lagtInnAv.NAV.bruker': 'NAV',
'lagtInnAv.NAV.veileder': '{ endretAv, select,\n  undefined { NAV }\n  other { {endretAv} }\n}',
'modal.skjema.lagre': 'Lagre',
'mote-aktivitet-form.feilmelding.adresse-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'mote-aktivitet-form.feilmelding.beskrivelse-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'mote-aktivitet-form.feilmelding.forberedelser-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'mote-aktivitet-form.feilmelding.pakrevd-adresse': 'Du må fylle ut møtested eller annen praktisk informasjon',
'mote-aktivitet-form.feilmelding.pakrevd-dato': 'Du må fylle ut dato for møtet',
'mote-aktivitet-form.feilmelding.pakrevd-kanal': 'Du må fylle ut møteform',
'mote-aktivitet-form.feilmelding.pakrevd-klokkeslett': 'Du må fylle ut klokkeslett',
'mote-aktivitet-form.feilmelding.pakrevd-tittel': 'Du må fylle ut tema for møtet',
'mote-aktivitet-form.feilmelding.pakrevd-varighet': 'Du må fylle ut varighet',
'mote-aktivitet-form.feilmelding.tittel-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'mote-aktivitet-form.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'mote-aktivitet-form.header': 'Møte med NAV',
'mote-aktivitet-form.label.adresse': 'Møtested eller annen praktisk informasjon *',
'mote-aktivitet-form.label.bakgrunn': 'Hensikt med møtet',
'mote-aktivitet-form.label.dato': 'Dato *',
'mote-aktivitet-form.label.forberedelser': 'Forberedelser til møtet',
'mote-aktivitet-form.label.kanal': 'Møteform *',
'mote-aktivitet-form.label.klokkeslett': 'Klokkeslett *',
'mote-aktivitet-form.label.overskrift': 'Tema for møtet *',
'mote-aktivitet-form.label.varighet': 'Varighet *',
'mote.varsling.forhandsorientering': 'Brukeren får ikke automatisk informasjon om møtet. Send en dialog eller forhåndsorientering for at brukeren skal få beskjed.',
'mote.varsling.ingen-dialog': 'Husk at du må sende en dialog eller et varsel for at brukeren skal få beskjed om møtet.',
'navigasjon.dialog': 'Dialog',
'navigasjon.informasjon': 'Om tjenesten',
'ny-aktivitet-modal.tilbake': 'Tilbake til kategorier',
'nyaktivitetsknapp': 'Legg til aktivitet',
'oppdater-aktivitet-etikett.header': 'Oppdater tilstand',
'oppdater-aktivitet-status.header': 'Oppdater status',
'oppfolging.ikke-under-oppfolging.reaktiveres.lenke-tekst': 'Gå til registrering',
'oppfolging.ikke-under-oppfolging': 'Denne brukeren er ikke lenger under oppfølging.',
'oppfolging.inaktivert-28-til-10-dager.reaktiveres': 'Du er ikke lenger registrert hos NAV. Hvis du fortsatt skal motta ytelser, få oppfølging fra NAV og bruke aktivitetsplanen må du være registrert.',
'oppfolging.inaktivert-mer-enn-28-dager.reaktiveres': 'Du er ikke lenger registrert hos NAV og din tidligere aktivitetsplan er lagt under "Tidligere plan". Hvis du fortsatt skal motta ytelser og få oppfølging fra NAV må du være registrert.',
'oppfolging.inaktivert-mindre-enn-10-dager.reaktiveres': 'Du er ikke lenger registrert hos NAV. Hvis du fortsatt skal motta ytelser, få oppfølging fra NAV og bruke aktivitetsplanen må du være registrert. Om {antalldagerIgjen} dager vil denne aktivitetsplanen bli avsluttet.',
'oppfolgning.bruker.bruker-er-eskalert.lenke-tekst': 'Les hva du må gjøre.',
'oppfolgning.bruker.bruker-er-eskalert': 'Du har fått en viktig melding fra NAV.',
'opprett-begrunnelse.avbrutt.header': 'Avbrutt aktivitet',
'opprett-begrunnelse.avbrutt.melding': 'Skriv en kort begrunnelse under om hvorfor du avbrøt aktiviteten. Når du lagrer blir aktiviteten låst, og du kan ikke lenger redigere innholdet. Etter at du har lagret, må du gi beskjed til  veilederen din ved å starte en dialog her i aktivitetsplanen.',
'opprett-begrunnelse.fullfoert.header': 'Fullført aktivitet',
'opprett-begrunnelse.fullfoert.melding': 'Skriv en kort kommentar om hvordan det har gått, eller noe NAV bør kjenne til. Når du lagrer, blir aktiviteten låst og du kan ikke lenger endre innholdet.',
'opprett-begrunnelse.melding.feilmelding.for-kort': 'Du må fylle ut en begrunnelse',
'opprett-begrunnelse.melding.feilmelding.for-lang': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'periode-filter.tittel': 'Mine tidligere planer',
'print-melding-form.beskrivelse-standardtekst': 'Her finner du avtalte aktiviteter med NAV som du skal gjennomføre for å nå målet ditt. Gi beskjed til NAV hvis det skjer endringer i situasjonen din eller hvis du ikke kan gjennomføre en aktivitet.',
'print-melding-form.feilmelding.beskrivelse-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'print-melding-form.feilmelding.overskrift-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'print-melding-form.feilmelding.pakrevd-overskrift': 'Du må fylle ut en overskrift',
'print-melding-form.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'print-melding-form.header': 'Aktivitetsplan for {FORNAVN}',
'print-melding-form.label.beskrivelse': 'Rediger teksten under så den passer til brukeren.',
'print-melding-form.label.overskrift': 'Overskrift *',
'print-melding-form.lagre': 'Velg',
'print.aktivitetsplan.beskrivelse': 'Du skriver ut alt innholdet du ser i aktivitetsplan, uten om KVP-perioden',
'print.aktivitetsplan': 'Oppfølgingsperioden uten KVP-perioden',
'print.hele.plan.beskrivelse': 'Du skriver ut alt innholdet du ser i aktivitetsplan, også KVP-perioden',
'print.hele.plan': 'Hele oppfølgingsperioden',
'print.kvp-plan-periode': '{fra} - {til}',
'print.kvp-plan.beskrivelse': 'Du skriver ut innholdet i KVP-perioden',
'print.kvp-plan': 'KVP-perioden',
'print.manuellbruker.eller.niva4': '{ erManuell, select, true { Manuell bruker } false { Pålogget nivå 4 }}',
'print.modal.tilbake': 'Tilbake',
'print.modal.utskrift.dato': 'Dato:',
'print.modal.utskrift.fnr': 'Fødselsnummer:',
'print.modia.oppfolging': 'Modia Arbeidsrettet Oppfølging',
'print.oppfolgingperiode': 'Periode: {fra} - {til}',
'print.velg.type': 'Velg hva du ønsker å skrive ut',
'referat.form.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'referat.form.lagre': 'Lagre',
'referat.form.pakrevd-referat': 'Du må fylle ut samtalereferat',
'referat.form.placeholder': 'Skriv samtalereferatet her',
'referat.form.publiser': 'Del',
'referat.form.referat-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'referat.header': 'Samtalereferat',
'referat.oppdater': 'Oppdater',
'referat.publiser': 'Del',
'referat.validering.ikke-publisert': 'Samtalereferatet må deles før du kan sette aktiviteten til denne statusen',
'samtalereferat-form.feilmelding.pakrevd-dato': 'Du må fylle ut dato for samtalen',
'samtalereferat-form.feilmelding.pakrevd-kanal': 'Du må fylle ut samtaleform',
'samtalereferat-form.feilmelding.pakrevd-referat': 'Du må fylle ut samtalereferat',
'samtalereferat-form.feilmelding.pakrevd-tittel': 'Du må fylle ut tema for samtalen',
'samtalereferat-form.feilmelding.referat-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'samtalereferat-form.feilmelding.tittel-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'samtalereferat-form.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'samtalereferat-form.header': 'Samtalereferat',
'samtalereferat-form.label.dato': 'Dato *',
'samtalereferat-form.label.kanal': 'Møteform *',
'samtalereferat-form.label.overskrift': 'Tema for samtalen *',
'samtalereferat-form.label.referat': 'Samtalereferat *',
'samtalereferat-form.placeholder.referat': 'Skriv her',
'satt-til-avtalt.tekst': 'Aktiviteten er nå merket "Avtalt med NAV"',
'sett-avltalt-tekst-som-sendes': 'Tekst til brukeren',
'sett-avtalt-bekreftelse': '{settAvtaltTekstVerdi, select,\n    erManuellKrrKvpBruker { Aktiviteten er merket "Avtalt med NAV" og forhåndsorientering er ikke sendt. }\n    forhandsorienteringIkkeSent { Aktiviteten er merket "Avtalt med NAV" og forhåndsorientering er ikke sendt. }\n    forhandsorienteringSent {{forhandsorienteringType, select,\n       send_forhandsorientering { Aktiviteten er merket "Avtalt med NAV" og forhåndsorientering (standard melding) er sendt. }\n       send_paragraf_11_9 { Aktiviteten er merket "Avtalt med NAV" og forhåndsorientering for §11-9 (AAP) er sendt. }\n       other { Aktiviteten er merket "Avtalt med NAV". Forhåndsorientering er sendt.}\n    }}\n    avtaltMedNavMindreEnnSyvDager { Aktiviteten er merket "Avtalt med NAV". Forhåndsorientering er ikke sendt, men brukeren skal være informert om mulige konsekvenser for ytelse og du skal ha dokumentert dette. }\n    other { Aktiviteten er merket "Avtalt med NAV". Forhåndsorientering er ikke sendt.}\n}',
'sett-avtalt-forhandsorientering-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'sett-avtalt-forhandsorientering-tekst': 'Det er viktig at du gjennomfører denne aktiviteten med NAV. Gjør du ikke det, kan det medføre at stønaden du mottar fra NAV bortfaller for en periode eller stanses. Hvis du ikke kan gjennomføre aktiviteten, ber vi deg ta kontakt med veilederen din så snart som mulig.',
'sett-avtalt-forhandsrientering-bruker-uten-aktivitesplan': '{brukerUtenAktivitesplan, select,\nbrukerErManuell { Du kan ikke sende forhåndsorientering fordi brukeren er manuell bruker. }\nbrukerErUnderKvp { Du kan ikke sende forhåndsorientering fordi brukeren deltar i kvalifiseringsprogrammet. }\nbrukerErIReservasjonKRR { Du kan ikke sende forhåndsorientering fordi brukeren har reservert seg i kontakt- og reservasjonsregisteret. }\nother { Du kan ikke sende forhåndsorientering på grunn av { brukerUtenAktivitesplan } }\n}',
'sett-avtalt-ikke-send-forhandsorientering': 'Ikke send forhåndsorientering',
'sett-avtalt-paragraf-11-9-tekst': 'Du kan få redusert utbetaling av arbeidsavklaringspenger med én stønadsdag hvis du lar være å [komme på møtet vi har innkalt deg til [dato]/ møte på … /levere ... innen [dato]] uten rimelig grunn. Dette går fram av folketrygdloven § 11-9.',
'sett-avtalt-send-forhandsorientering': 'Send forhåndsorientering (standard melding)',
'sett-avtalt-send-paragraf-11-9': 'Send forhåndsorientering for §11-9 (AAP)',
'sett-avtalt-teskt-som-sendes-hjelpetekst': 'Brukeren får en SMS eller e-post via kontaktinformasjon som brukeren selv har registrert i det offentlige kontaktregisteret. Brukeren får beskjed om en viktig oppgave og det lenkes til dialog. Beskjeden sendes gjennom Altinn etter en halv time. Sender du flere forhåndsorienteringer innen en halv time så blir det kun sendt én SMS eller e-post.',
'sett-avtalt-velg-type': 'Velg type forhåndsorientering',
'sett-avtalt.header': 'Merk aktiviteten som "Avtalt med NAV"',
'sett-avtalt.hjelpetekst': 'Aktiviteter som oppfyller brukerens aktivitets- og medvirkningsplikt skal settes som "Avtalt med NAV"',
'sett-avtalt.label': 'Avtalt med NAV',
'sett-avtalt.paakrevd-forhandsorientering': 'Du må fylle ut en forhåndsorientering',
'sett-digital.begrunnelse.for-kort': 'Du må fylle ut en begrunnelse',
'sett-digital.manuell-oppfolging.aktiver-digital-knapp': 'Endre til digital oppfølging',
'sett-digital.manuell-oppfolging.infotekst': 'Du får ikke digital oppfølging fra NAV og har derfor ikke tilgang til din digitale aktivitetsplan. Klikk på knappen under hvis du ønsker å endre dette.',
'sett-digital.manuell-oppfolging.reservasjon-difi-knapp': 'Jeg har fjernet reservasjonen',
'sett-digital.reservert-i-krr.fjern.reservasjon.infotekst': 'For å ta i bruk den digitale aktivitetsplanen, må du fjerne reservasjonen din mot digital kommunikasjon.',
'sett-digital.reservert-i-krr.infotekst': 'Du har reservert deg mot digital kommunikasjon og kan derfor ikke bruke den digitale aktivitetsplanen.',
'sett-digital.reservert-i-krr.lenketekst': 'Gå til Norge.no for å fjerne reservasjonen',
'sett-digital.reservert-i-krr.url-lenke': 'https://www.norge.no/nn/reservasjon',
'sett-forhandsorienterings-tekst-arena-aktivitet': 'Du kan få redusert utbetaling av arbeidsavklaringspenger med én stønadsdag hvis du lar være å [komme på møtet vi har innkalt deg til [dato]/ møte på … /levere ... innen [dato]] uten rimelig grunn. Dette går fram av folketrygdloven § 11-9.',
'sett-manuell.begrunnelse.for-kort': 'Du må fylle ut en begrunnelse',
'sett-til-avtalt-mindre-enn-syv-dager': 'Du kan ikke sende forhåndsorientering fordi du har satt sluttdatoen til mindre enn 7 dager frem i tid. Hvis du har hatt muntlig dialog med brukeren om mulige konsekvenser for ytelse og dokumentert dette i et samtalereferat, så kan du sette aktiviteten til "Avtalt med NAV".',
'sett-til-avtalt.bekreft-knapp': '{ikkeSend, select,\ntrue { Bekreft }\nfalse { Bekreft og send }\n}',
'slett-filter': 'Slett filter',
'sokeavtale-aktivitet-form.default-tittel': 'Avtale om å søke jobber',
'sokeavtale-aktivitet-form.feilmelding.beskrivelse-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'sokeavtale-aktivitet-form.feilmelding.numerisk-antall': 'Antall må være et heltall',
'sokeavtale-aktivitet-form.feilmelding.oppfolging-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'sokeavtale-aktivitet-form.feilmelding.paakrevd-antall': 'Du må fylle ut antall søknader i perioden',
'sokeavtale-aktivitet-form.feilmelding.paakrevd-fradato': 'Du må fylle ut fra dato',
'sokeavtale-aktivitet-form.feilmelding.paakrevd-tildato': 'Du må fylle ut til dato',
'sokeavtale-aktivitet-form.feilmelding.soknad-antall': 'Antall søknader i perioden kan ikke være større enn {MAKS_LENGDE}',
'sokeavtale-aktivitet-form.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'sokeavtale-aktivitet-form.header': 'Avtale om å søke jobber',
'sokeavtale-aktivitet-form.label.antall': 'Antall søknader i perioden *',
'sokeavtale-aktivitet-form.label.avtale-oppfolging': 'Oppfølging fra NAV',
'sokeavtale-aktivitet-form.label.beskrivelse': 'Beskrivelse',
'sokeavtale-aktivitet-form.label.fra-dato': 'Fra dato *',
'sokeavtale-aktivitet-form.label.overskrift': 'Type aktivitet',
'sokeavtale-aktivitet-form.label.til-dato': 'Til dato *',
'start.eskalering.begrunnelse.for-kort': 'Du må fylle ut et varsel som skal sendes til brukeren',
'start.kvp.begrunnelse.for-kort': 'Du må fylle ut en begrunnelse',
'stilling-aktivitet-form.feilmelding.arbeidsgiver-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'stilling-aktivitet-form.feilmelding.arbeidssted-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'stilling-aktivitet-form.feilmelding.beskrivelse-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'stilling-aktivitet-form.feilmelding.kontaktperson-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'stilling-aktivitet-form.feilmelding.lenke-lengde': 'Lenken kan ikke være lenger enn {MAKS_LENGDE} tegn',
'stilling-aktivitet-form.feilmelding.paakrevd-fradato': 'Du må fylle ut fra dato',
'stilling-aktivitet-form.feilmelding.paakrevd-tildato': 'Du må fylle ut søknadsfrist',
'stilling-aktivitet-form.feilmelding.paakrevd-tittel': 'Du må fylle ut stillingstittel',
'stilling-aktivitet-form.feilmelding.tittel-lengde': 'Du må korte ned teksten til {MAKS_LENGDE} tegn',
'stilling-aktivitet-form.feiloppsummering-tittel': 'Fyll ut obligatoriske felt',
'stilling-aktivitet-form.header': 'En jobb jeg vil søke på',
'stilling-aktivitet-form.label.arbeidsgiver': 'Arbeidsgiver',
'stilling-aktivitet-form.label.arbeidssted': 'Arbeidssted',
'stilling-aktivitet-form.label.beskrivelse': 'Kort beskrivelse av stillingen',
'stilling-aktivitet-form.label.fra-dato': 'Fra dato*',
'stilling-aktivitet-form.label.kontaktperson': 'Kontaktperson hos arbeidsgiver',
'stilling-aktivitet-form.label.lenke': 'Lenke til stillingsannonse',
'stilling-aktivitet-form.label.overskrift': 'Stillingstittel *',
'stilling-aktivitet-form.label.til-dato': 'Frist',
'stop.kvp.begrunnelse.for-kort': 'Du må fylle ut en begrunnelse',
'stopp.eskalering.begrunnelse.for-kort': 'Du må fylle ut en begrunnelse',
'tall-alert-etter-antall': 'uleste meldinger',
'tall-alert-foran-antall': 'Du har',
'tall-alert.antall.skjermleser': 'Du har {ULESTE_MELDINGER, plural,\n    one { # ulest melding}\n    other { # uleste meldinger }\n}',
'tekstfelt.antalltegn.flere-igjen': 'Du har {antall} tegn igjen',
'tekstfelt.antalltegn.for-mange': 'Du har {antall} tegn for mye',
'timeoutbox.aria.label': 'Advarsel om utlogging',
'timeoutbox.innhold.loggetut': 'Sesjonen har utløpt. Du må logge inn igjen for å fortsette.',
'timeoutbox.innhold.nedtelling': 'Din sesjon vil utløpe om {tid} minutter. Dersom du ikke laster siden på nytt, vil du bli logget ut. Ta vare på alt ulagret arbeid. For å laste siden på nytt, vennligst trykk "Last siden på nytt".',
'timeoutbox.knapp.last_pa_nytt': 'Last siden på nytt',
'timeoutbox.knapp.loggut': 'Logg ut',
'timeoutbox.tittel': 'Obs!',
'toolbar.tildel-veileder': 'Tildel veileder',
'utskrift.ikon.alt.tekst': 'Skriv ut aktivitetsplanen',
'vis-eldre-aktiviteter-intro': 'Aktivitetskort som er eldre enn to måneder vises ikke.'
 } };