name: Deploy alerts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'alerts/alerts.yml'
      - '.github/workflows/alerts.yml'

concurrency:
  group: deploy_alerts
  cancel-in-progress: true

jobs:
  apply-alerts-dev:
    name: Apply alerts til dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: deploy alerts to dev
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: dev-gcp
          RESOURCE: alerts/alerts.yml

  apply-alerts-prod:
    name: Apply alerts til prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: deploy alerts to prod
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts/alerts.yml
