name: deploy asseets

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/pto-frontend-container-prod.yml'
      - 'nais/prod-intern.yaml'
      - 'nais/prod-ekstern.yaml'
      - 'nais/dev-intern.yaml'
      - 'nais/dev-ekstern.yaml'

concurrency:
  group: deploy-assets
  cancel-in-progress: true

jobs:
  prod-ekstern:
    name: Deploy application to prod ekstern
    uses: navikt/aktivitetsplan/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build-ekstern-prod
      bucket: aktivitetsplan-prod
      releaseName: prod-ekstern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_PROD }}
  prod-intern:
    name: Deploy application to prod intern
    uses: navikt/aktivitetsplan/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build-intern-prod
      bucket: aktivitetsplan-prod-intern
      releaseName: prod-intern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_PROD }}
