name: deploy dev og prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
  packages: 'write'

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install pnpm - setup node - install deps
        uses: ./.github/actions/setup-pnpm
        with:
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run tests
        run: pnpm run test

  dev-ekstern:
    name: Deploy to dev extern
    needs: test
    uses: ./.github/workflows/deploy-ekstern.yml
    with:
      kommando: pnpm run build:dev-ekstern
      bucket: aktivitetsplan-dev-ekstern
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}

  dev-intern:
    name: Deploy application to dev intern
    needs: test
    uses: ./.github/workflows/deploy-intern.yml
    with:
      kommando: pnpm run build:dev-intern
      bucket: aktivitetsplan-dev-intern
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}

  prod-ekstern:
    name: Deploy application to prod ekstern
    needs: dev-ekstern
    uses: ./.github/workflows/deploy-ekstern.yml
    with:
      kommando: pnpm run build:prod-ekstern
      bucket: aktivitetsplan-prod-ekstern
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  prod-intern:
    name: Deploy application to prod intern
    needs: dev-intern
    uses: ./.github/workflows/deploy-intern.yml
    with:
      kommando: pnpm run build:prod-intern
      bucket: aktivitetsplan-prod-intern
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
