name: Migrate namespace

on:
  schedule:
    - cron: '0 4 * * *' # 06:00 CEST (UTC+2) / 05:00 CET (UTC+1)
  workflow_dispatch:

concurrency:
  group: migrate_namespace
  cancel-in-progress: false

jobs:
  fjern-dev-ingress:
    name: Fjern ingress fra pto namespace i dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Deploy dev-ekstern-old
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-ekstern.yaml
          VARS: nais/pto/dev-pto-remove-ingress.yaml
      - name: Slack Notification (deploy failure)
        if: failure()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Aktivitetsplan: migrate namespace - deploy av dev-ekstern-old feilet'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Migrate namespace workflow feilet på dev-ekstern-old'

  fjern-prod-ingress:
    name: Fjern ingress fra pto namespace i prod
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Deploy prod-ekstern-old
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-ekstern.yaml
          VARS: nais/pto/prod-pto-remove-ingress.yaml
      - name: Slack Notification (deploy failure)
        if: failure()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Aktivitetsplan: migrate namespace - deploy av prod-ekstern-old feilet'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Migrate namespace workflow feilet på prod-ekstern-old'

  deploy-dev-ekstern:
    name: Legg til ingress i dab namespace i dev
    needs: [fjern-dev-ingress]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Deploy dev-ekstern
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-ekstern.yaml
          VARS: nais/dab/dev-dab-with-ingress.yaml
      - name: Slack Notification (deploy failure)
        if: failure()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Aktivitetsplan: migrate namespace - deploy av dev-ekstern feilet'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Migrate namespace workflow feilet på dev-ekstern'

  deploy-prod-ekstern:
    name: Legg til ingress i dab namespace i prod
    needs: [fjern-prod-ingress]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Deploy prod-ekstern
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-ekstern.yaml
          VARS: nais/dab/prod-dab-with-ingress.yaml
      - name: Slack Notification (deploy failure)
        if: failure()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Aktivitetsplan: migrate namespace - deploy av prod-ekstern feilet'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Migrate namespace workflow feilet på prod-ekstern'

  rollback-dev-ekstern:
    name: Rollback - gjenopprett ingress i pto namespace i dev
    needs: [fjern-dev-ingress, deploy-dev-ekstern]
    if: ${{ always() && needs.fjern-dev-ingress.result == 'success' && needs.deploy-dev-ekstern.result == 'failure' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Rollback til pto namespace i dev
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev-ekstern.yaml
          VARS: nais/pto/dev-pto-fallback.yaml
      - name: Slack Notification (rollback success)
        if: success()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_COLOR: warning
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Aktivitetsplan: migrate namespace - rullet tilbake til pto namespace i dev'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Deploy til dab feilet. App er gjenopprettet i pto namespace i dev'
      - name: Slack Notification (rollback failure)
        if: failure()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Aktivitetsplan: migrate namespace - rollback til pto namespace i dev feilet'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Migrate namespace rollback feilet for dev - manuell handling nødvendig'

  rollback-prod-ekstern:
    name: Rollback - gjenopprett ingress i pto namespace i prod
    needs: [fjern-prod-ingress, deploy-prod-ekstern]
    if: ${{ always() && needs.fjern-prod-ingress.result == 'success' && needs.deploy-prod-ekstern.result == 'failure' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Rollback til pto namespace i prod
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/prod-ekstern.yaml
          VARS: nais/pto/prod-pto-fallback.yaml
      - name: Slack Notification (rollback success)
        if: success()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_COLOR: warning
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Aktivitetsplan: migrate namespace - rullet tilbake til pto namespace i prod'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Deploy til dab feilet. App er gjenopprettet i pto namespace i prod'
      - name: Slack Notification (rollback failure)
        if: failure()
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Aktivitetsplan: migrate namespace - rollback til pto namespace i prod feilet'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Migrate namespace rollback feilet for prod - manuell handling nødvendig'
