name: Test on push/workflow_dispatch

on: [push, workflow_dispatch]

env:
  PRINT_PAYLOAD: true

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-pnpm
        name: Install pnpm - setup node - install deps
        with:
          READER_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: pnpm run typecheck
      - run: pnpm run lint
      - run: pnpm run coverage
      - run: pnpm run build
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@ba9859eae8dd6bd29e412f25ddbbef3d032000f4 # v8.2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
